[package]
name = "argten-backend-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
rand = "0.8.5"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
show-image = "0.14.0"
