[workspace]
members = ["shared", "viewer"]

[package]
name = "artgen-backend-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
artgen-shared = { path = "shared" }
anyhow = "1.0.102"
base64 = "0.22"
bytemuck = { version = "1.25.0", features = ["derive"] }
divan = "0.1.21"
futures = "0.3.32"
futures-intrusive = "0.5.0"
futures-lite = "2.6.1"
image = "0.25.9"
num_cpus = "1.17.0"
rand = "0.10.0"
sdl2 = "0.38.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "sync"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["fmt", "env-filter"] }
tungstenite = "0.28"
wgpu = "28.0.0"

[[bench]]
name = "bench"
harness = false

[profile.release]
opt-level = 3
debug = true
strip = "none"
debug-assertions = false
overflow-checks = false
lto = false
panic = 'abort'
incremental = true
codegen-units = 1
rpath = true

[profile.bench]
inherits = "release"
