server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        try_files $uri /index.html;
    }

    location /data/ {
        alias /data/;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
